# Generated by Django 4.0.6 on 2023-09-14 03:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0002_friendrequest_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequest',
            new_name='FriendshipRequest',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='friend',
            new_name='friends',
        ),
    ]
