# Generated by Django 4.0.6 on 2023-09-14 03:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0004_alter_chatroomcontent_chatroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chatroom',
            new_name='Interface',
        ),
        migrations.RenameModel(
            old_name='ChatroomContent',
            new_name='InterfaceContent',
        ),
    ]
